=== AndrYurk/tutorial-resources/icc-irs-challenges/job-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "job": {
      "type": "object",
      "properties": {
        "id": { "type": "string", "format": "uuid" },
        "globalAssetId": { "type": "string" },
        "state": { "type": "string" },
        "exception": { "type": ["null", "string"] },
        "createdOn": { "type": "string", "format": "date-time" },
        "startedOn": { "type": "string", "format": "date-time" },
        "lastModifiedOn": { "type": "string", "format": "date-time" },
        "completedOn": { "type": "string", "format": "date-time" },
        "summary": {
          "type": "object",
          "properties": {
            "asyncFetchedItems": {
              "type": "object",
              "properties": {
                "running": { "type": "integer" },
                "completed": { "type": "integer" },
                "failed": { "type": "integer" }
              },
              "required": ["running", "completed", "failed"]
            }
          },
          "required": ["asyncFetchedItems"]
        },
        "parameter": {
          "type": "object",
          "properties": {
            "bomLifecycle": { "type": "string" },
            "aspects": {
              "type": "array",
              "items": { "type": "string" }
            },
            "depth": { "type": "integer" },
            "bpn": { "type": "string" },
            "direction": { "type": "string" },
            "collectAspects": { "type": "boolean" },
            "lookupBPNs": { "type": "boolean" },
            "auditContractNegotiation": { "type": "boolean" },
            "callbackUrl": { "type": ["null", "string"], "format": "uri" }
          },
          "required": ["bomLifecycle", "aspects", "depth", "bpn", "direction", "collectAspects", "lookupBPNs", "auditContractNegotiation"]
        }
      },
      "required": ["id", "globalAssetId", "state", "exception", "createdOn", "startedOn", "lastModifiedOn", "completedOn", "summary", "parameter"]
    },
    "relationships": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "catenaXId": { "type": "string" },
          "linkedItem": {
            "type": "object",
            "properties": {
              "quantity": {
                "type": "object",
                "properties": {
                  "quantityNumber": { "type": "number" },
                  "measurementUnit": {
                    "type": "object",
                    "properties": {
                      "datatypeURI": { "type": ["null", "string"] },
                      "lexicalValue": { "type": "string" }
                    },
                    "required": ["lexicalValue"]
                  }
                },
                "required": ["quantityNumber", "measurementUnit"]
              },
              "lifecycleContext": { "type": "string" },
              "assembledOn": { "type": "string", "format": "date-time" },
              "lastModifiedOn": { "type": "string", "format": "date-time" },
              "childCatenaXId": { "type": "string" },
              "hasAlternatives": { "type": "boolean" }
            },
            "required": ["quantity", "lifecycleContext", "assembledOn", "lastModifiedOn", "childCatenaXId", "hasAlternatives"]
          },
          "aspectType": { "type": "string" },
          "bpn": { "type": "string" }
        },
        "required": ["catenaXId", "linkedItem", "aspectType", "bpn"]
      }
    },
    "shells": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "contractAgreementId": { "type": "string", "format": "uuid" },
          "payload": {
            "type": "object",
            "properties": {
              "administration": { "type": ["null", "object"] },
              "description": { "type": "array", "items": { "type": "string" } },
              "globalAssetId": { "type": "string" },
              "idShort": { "type": "string" },
              "id": { "type": "string" },
              "specificAssetIds": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": { "type": "string" },
                    "subjectId": { "type": ["null", "string"] },
                    "externalSubjectId": {
                      "type": "object",
                      "properties": {
                        "keys": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "value": { "type": "string" },
                              "type": { "type": "string" }
                            },
                            "required": ["value", "type"]
                          }
                        },
                        "type": { "type": "string" }
                      },
                      "required": ["keys", "type"]
                    },
                    "value": { "type": "string" },
                    "semanticId": { "type": ["null", "string"] }
                  },
                  "required": ["name", "externalSubjectId", "value"]
                }
              },
              "submodelDescriptors": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "administration": { "type": ["null", "object"] },
                    "description": { "type": "array", "items": { "type": "string" } },
                    "idShort": { "type": "string" },
                    "id": { "type": "string" },
                    "semanticId": {
                      "type": "object",
                      "properties": {
                        "keys": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "value": { "type": "string" },
                              "type": { "type": "string" }
                            },
                            "required": ["value", "type"]
                          }
                        },
                        "type": { "type": "string" }
                      },
                      "required": ["keys", "type"]
                    },
                    "endpoints": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "protocolInformation": {
                            "type": "object",
                            "properties": {
                              "href": { "type": "string", "format": "uri" },
                              "endpointProtocol": { "type": "string" },
                              "endpointProtocolVersion": {
                                "type": "array",
                                "items": { "type": "string" }
                              },
                              "subprotocol": { "type": "string" },
                              "subprotocolBody": { "type": "string" },
                              "subprotocolBodyEncoding": { "type": "string" },
                              "securityAttributes": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "type": { "type": "string" },
                                    "key": { "type": "string" },
                                    "value": { "type": "string" }
                                  },
                                  "required": ["type", "key", "value"]
                                }
                              }
                            },
                            "required": ["href", "endpointProtocol", "endpointProtocolVersion", "subprotocol", "subprotocolBody", "subprotocolBodyEncoding", "securityAttributes"]
                          },
                          "interface": { "type": "string" }
                        },
                        "required": ["protocolInformation", "interface"]
                      }
                    }
                  },
                  "required": ["idShort", "id", "semanticId", "endpoints"]
                }
              }
            },
            "required": ["globalAssetId", "idShort", "id", "specificAssetIds", "submodelDescriptors"]
          }
        },
        "required": ["contractAgreementId", "payload"]
      }
    },
    "tombstones": { "type": "array" },
    "submodels": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "identification": { "type": "string" },
          "aspectType": { "type": "string" },
          "contractAgreementId": { "type": "string" },
          "payload": { "type": "object" }
        },
        "required": ["identification", "aspectType", "contractAgreementId", "payload"]
      }
    },
    "bpns": { "type": "array" }
  },
  "required": ["job", "relationships", "shells", "tombstones", "submodels", "bpns"]
}

=== AndrYurk/tutorial-resources/icc-irs-challenges/irs-job-response-structure.json
{
  "job": {
    "id": "8d4ed6a5-3d42-499f-97ba-2b718dfd91e4",
    "globalAssetId": "urn:uuid:4509ea7c-c8d2-41a1-83ca-c214ee34af6c",
    "state": "COMPLETED",
    "exception": null,
    "createdOn": "2024-11-27T07:51:10.91988319Z",
    "startedOn": "2024-11-27T07:51:10.920063894Z",
    "lastModifiedOn": "2024-11-27T07:51:44.054163487Z",
    "completedOn": "2024-11-27T07:51:44.054165687Z",
    "summary": {
      "asyncFetchedItems": {
        "running": 0,
        "completed": 10,
        "failed": 0
      }
    },
    "parameter": {
      "bomLifecycle": "asBuilt",
      "aspects": [
        "urn:samm:io.catenax.serial_part:3.0.0#SerialPart",
        "urn:samm:io.catenax.just_in_sequence_part:3.0.0#JustInSequencePart",
        "urn:samm:io.catenax.batch:3.0.0#Batch",
        "urn:samm:io.catenax.single_level_bom_as_built:3.0.0#SingleLevelBomAsBuilt"
      ],
      "depth": 100,
      "bpn": "BPNL00000003AXS3",
      "direction": "downward",
      "collectAspects": true,
      "lookupBPNs": false,
      "auditContractNegotiation": true,
      "callbackUrl": null
    }
  },
  "relationships": [
    {
      "catenaXId": "urn:uuid:4509ea7c-c8d2-41a1-83ca-c214ee34af6c",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000003B3NX"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:c9b677d7-de53-4da9-90e9-1f59acb6685e",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:d2f729b6-66b1-47b9-a87e-6150a0115e19",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:e8560e8c-7c92-44e2-9591-a5099bd09815",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:4d47dfb4-4af7-41a8-9d41-b11db51a4b4a",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:ae83cb68-bd73-4819-a782-b7bc6c042948",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:3372ed2c-56ea-4fc3-909b-d193a7721153",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:a5edeb5a-040e-42a6-a4a7-e098ff1121a8",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    },
    {
      "catenaXId": "urn:uuid:10bedf9c-b2e2-4cd8-bb55-290107cceb09",
      "linkedItem": {
        "quantity": {
          "quantityNumber": 20.0,
          "measurementUnit": {
            "datatypeURI": null,
            "lexicalValue": "unit:piece"
          }
        },
        "lifecycleContext": "asBuilt",
        "assembledOn": "2022-02-03T14:48:54.709Z",
        "lastModifiedOn": "2022-02-03T14:48:54.709Z",
        "childCatenaXId": "urn:uuid:6fec45b1-fa4d-487f-8418-b4bbc2955fbd",
        "hasAlternatives": false
      },
      "aspectType": "SingleLevelBomAsBuilt",
      "bpn": "BPNL00000000BJTL"
    }
  ],
  "shells": [
    {
      "contractAgreementId": "b329a6cd-cea1-4258-98d7-086c5128dab9",
      "payload": {
        "administration": null,
        "description": [],
        "globalAssetId": "urn:uuid:4509ea7c-c8d2-41a1-83ca-c214ee34af6c",
        "idShort": "VehicleFullyElectric-38d01f3d434e4f92808688907e8288ed",
        "id": "urn:uuid:a9f28808-18e0-4f80-b6e9-ec3ee86a6bc6",
        "specificAssetIds": [
          {
            "name": "manufacturerId",
            "subjectId": null,
            "externalSubjectId": {
              "keys": [
                {
                  "value": "BPNL00000003AXS3",
                  "type": "GlobalReference"
                }
              ],
              "type": "ExternalReference"
            },
            "value": "BPNL00000003AVTH",
            "semanticId": null
          },
          {
            "name": "van",
            "subjectId": null,
            "externalSubjectId": {
              "keys": [
                {
                  "value": "BPNL00000003AXS3",
                  "type": "GlobalReference"
                }
              ],
              "type": "ExternalReference"
            },
            "value": "OMBXAFHRPALTYNHWL",
            "semanticId": null
          },
          {
            "name": "digitalTwinType",
            "subjectId": null,
            "externalSubjectId": {
              "keys": [
                {
                  "value": "PUBLIC_READABLE",
                  "type": "GlobalReference"
                },
                {
                  "value": "BPNL00000003AXS3",
                  "type": "GlobalReference"
                }
              ],
              "type": "ExternalReference"
            },
            "value": "PartInstance",
            "semanticId": null
          },
          {
            "name": "manufacturerId",
            "subjectId": null,
            "externalSubjectId": {
              "keys": [
                {
                  "value": "BPNL00000003AXS3",
                  "type": "GlobalReference"
                }
              ],
              "type": "ExternalReference"
            },
            "value": "BPNL00000003AXS3",
            "semanticId": null
          },
          {
            "name": "partInstanceId",
            "subjectId": null,
            "externalSubjectId": {
              "keys": [
                {
                  "value": "BPNL00000003AXS3",
                  "type": "GlobalReference"
                }
              ],
              "type": "ExternalReference"
            },
            "value": "OMBXAFHRPALTYNHWL",
            "semanticId": null
          }
        ],
        "submodelDescriptors": [
          {
            "administration": null,
            "description": [],
            "idShort": "urn:samm:io.catenax.serial_part:3.0.0#SerialPart",
            "id": "urn:uuid:91065414-108b-430b-8258-d698ee31776e",
            "semanticId": {
              "keys": [
                {
                  "value": "urn:samm:io.catenax.serial_part:3.0.0#SerialPart",
                  "type": "GlobalReference"
                }
              ],
              "type": "ExternalReference"
            },
            "endpoints": [
              {
